name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: windows-latest  # Use Windows instead of Ubuntu
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: milindasandaru  # Replace with your GitHub username
          outputs: dist/snake.svg?palette=github-dark

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: main # Replace with your target branch if different
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.Snake_Secret_Token}}  # Replace with your secret name if using a custom token
